<MainWindow>:
    BoxLayout:
        id: main_box
        orientation: "vertical"
        BoxLayout:
            id: title
            orientation: "vertical"
            Label:
                text: "Format da compilare"
        BoxLayout:
            id: fields
            orientation: "vertical"
        BoxLayout:
            id: button
            orientation: "vertical"
            Button:
                text: "Ehi"